source 'https://rubygems.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'
gem 'faye-websocket'
gem 'thin'
#gem 'puma'

# Optional JSON codec (faster performance)
# gem 'oj'
gem 'oj' # missing dependency for gem 'padrino-websockets'

# Project requirements
gem 'rake'
gem 'padrino-websockets'
#gem 'padrino-websockets', :git => 'https://github.com/grillbiff/padrino-websockets.git'
gem 'rufus-scheduler'



# Component requirements
gem 'slim'

# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.12.3'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.12.3'
# end




